name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

# added ECR variables in github
env:
  ECR_REGISTRY: 975391844503.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: demo-app
  IMAGE_TAG: ${{ github.sha }}
  EKS_CLUSTER_NAME: test-eks
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Java application with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          echo "docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ."
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          echo " docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker images |grep -i demo-app
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Kubeconfig for EKS
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS using kubectl
        run: |
          NAMESPACE=java-app
          dep=java-app
          echo "Checking if $NAMESPACE namespace exists"
          if ! kubectl get namespace $NAMESPACE > /dev/null 2>&1; then
            echo "Namespace $NAMESPACE doesn't exist, creating it..."
            kubectl create namespace $NAMESPACE
          else
            echo "Namespace $NAMESPACE already exists"
          fi

          # Working on deployement
          echo "Chekcing if deployment $dep already exists.."
          if kubectl get deployment $dep -n $NAMESPACE > /dev/null 2>&1 ; then
            echo "Deployment $dep already exists, rolling updates..."
            kubectl set image deployment/$dep java-app=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} --record -n $NAMESPACE
            kubectl rollout status deployment/$dep -n $NAMESPACE

          else
            echo "Deployment $dep doesn't exists, creating it...."
            ls -l 
            kubectl apply -f ./k8s/deployment.yaml -n $NAMESPACE
            kubectl apply -f ./k8s/service.yaml -n $NAMESPACE
          fi
             

